namespace: jaydee_io
name: dlink_dgs1250
version: 0.3.0
readme: README.md
description: Ansible Collection for D-Link DGS-1250 Series Smart Managed Switch administration
license:
  - GPL-2.0-or-later
authors:
  - Jérôme Dumesnil
tags:
  - networking
  - dlink
  - switch
dependencies:
  ansible.netcommon: ">=2.0.0"
repository: https://github.com/jaydee-io/D-LinkAnsibleGalaxy
homepage: https://github.com/jaydee-io/D-LinkAnsibleGalaxy
issues: https://github.com/jaydee-io/D-LinkAnsibleGalaxy/issues
