---
# --- Create IP access lists ---
- name: Create IP access lists
  jaydee_io.dlink_dgs1250.acl_ip_access_list:
    name: "{{ item.name }}"
    extended: "{{ item.extended | default(false) }}"
  notify: Save config
  loop: "{{ acl_setup_ip_access_lists }}"
  when: acl_setup_ip_access_lists | length > 0

# --- Add rules to each access list ---
- name: Add rules to IP access lists
  jaydee_io.dlink_dgs1250.acl_rule_ip:
    acl_name: "{{ item.0.name }}"
    extended: "{{ item.0.extended | default(false) }}"
    rule: "{{ item.1 }}"
  notify: Save config
  loop: "{{ acl_setup_ip_access_lists | subelements('rules', skip_missing=True) }}"
  when: acl_setup_ip_access_lists | length > 0

# --- Apply access lists to interfaces ---
- name: Apply IP access lists to interfaces
  jaydee_io.dlink_dgs1250.acl_ip_access_group:
    interface: "{{ item.interface }}"
    name: "{{ item.acl_name }}"
  notify: Save config
  loop: "{{ acl_setup_interface_bindings }}"
  when: acl_setup_interface_bindings | length > 0
