---
galaxy_info:
  author: "Jérôme Dumesnil"
  description: "Configure static routes on a D-Link DGS-1250 switch: IPv4 and IPv6 routes"
  license: "GPL-2.0-or-later"
  min_ansible_version: "2.15"
  galaxy_tags:
    - networking
    - routing
    - dlink

dependencies: []
